quality<- read.csv("D:\\A029_TYIT_Aaditya\\TYIT-6TH-SEM\\BI\\Pracs\\Resources\\quality.csv")
str(quality)
library(caTools)
set.seed(88)
split= sample.split(quality$PoorCare,SplitRatio=0.75)
print(split)
qualityTrain=subset(quality,split==TRUE)
qualityTest=subset(quality,split==FALSE)
#numrows
nrow(qualityTrain)
nrow(qualityTest)
QualityLog=glm(PoorCare~OfficeVisits+Narcotics,data=qualityTrain,family=binomial)
summary(QualityLog)
predictTrain= predict(QualityLog,type="response")
summary(predictTrain)
tapply(predictTrain,qualityTrain$PoorCare,mean)
table(qualityTrain$PoorCare,predictTrain>0.5)
table(qualityTrain$PoorCare,predictTrain>0.2)
png(file='D:\\A029_TYIT_Aaditya\\TYIT-6TH-SEM\\BI\\Pracs\\R_prac_output\\logistic_regression.png')
library(ROCR)
ROCRpred=prediction(predictTrain,qualityTrain$PoorCare)
ROCRperf=performance(ROCRpred,"tpr","fpr")
plot(ROCRperf)
plot(ROCRperf,colorize=TRUE)
plot(ROCRperf,colorize=TRUE,print.cutoffs.at=seq(0,1,by=0.1),text.adj=c(-0.2,1.7))
dev.off()
